name=Waveshare_EPD
version=1.0.0
author= Wendy H. Chun
maintainer=Wendy H. Chun
sentence=Library for Waveshare 4.3 UART e-Paper Display
paragraph=Library for Waveshare 4.3 UART e-Paper Display
category=Display
url=https://github.com/whchun/waveshare-epd
architectures=*